In [1]:
import pickle
import os
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

DATAPATH = os.getenv("DATAPATH")
dataframes = pickle.load(open(DATAPATH+"april_cluster_row_col_dfs.pkl", "rb"))

In [2]:
import sys
sys.path.append("/home/hoangbaoan1901/Documents/information-system_UET/sem5/ai/BTL/INT3401-Midterm/LSTM_implementation")

In [ ]:
cluster_0 = dataframes[0] # 80 different dataframes
df = cluster_0[list(cluster_0.keys())[0]] # 1 dataframe

In [4]:
df.head()

date  aws  imerge      tclw      cape       r850       tcwv  \
0 2019-04-01 00:00:00  0.0     0.0  0.093994   930.250  93.015000  29.742813   
1 2019-04-01 01:00:00  0.0     0.0  0.114746   793.250  98.464480  30.253586   
2 2019-04-01 02:00:00  0.0     0.0  0.131409   806.750  91.836230  30.177887   
3 2019-04-01 03:00:00  0.0     0.0  0.156738  1029.125  94.334305  30.166610   
4 2019-04-01 04:00:00  0.0     0.0  0.139221  1225.750  93.738800  29.525208   

         tcw    isor         kx  ...      slor       b14b       b12b  \
0  29.839172  0.5082  32.119940  ...  0.034506  288.25058  262.22073   
1  30.370926  0.5082  31.468956  ...  0.034506  290.57855  263.76273   
2  30.322403  0.5082  31.187920  ...  0.034506  290.43240  263.85605   
3  30.324677  0.5082  30.806915  ...  0.034506  287.45575  262.18450   
4  29.665360  0.5082  30.228333  ...  0.034506  291.72513  265.35060   

         wvb       b10b       b11b        i2b       b09b       b16b        irb  
0  249.72734  266.46400  285.34500  286.39172  260.62613  272.37018  287.96760  
1  249.84330  267.04724  288.03770  288.17337  260.74150  273.22253  290.76288  
2  249.84330  267.04724  288.03436  287.78806  261.30444  272.86917  290.76178  
3  249.94067  266.46400  284.85562  285.19043  260.76400  271.51350  287.82123  
4  250.16780  266.26907  290.09470  288.09225  260.74150  272.51306  292.69412  

[5 rows x 24 columns]

# Test numpy accessing

In [7]:
import numpy as np

arr = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
arr = np.array(arr)

arr.shape

print(arr[0][-1])

last_row = arr[:, -1, :]
print(last_row)

[7 8 9]
[[ 7  8  9]
 [16 17 18]]
